name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up C++ Build Environment
      run: sudo apt-get install build-essential 


    - name: Set up Google Test
      run: |
        cd googletest
        cmake .
        make
        sudo make install
        cd ..

    - name: Build and Run Tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./runTests
